### ISSUE TITLE
Failing to run the simulation

### ISSUE THREAD

**Issue by NahomGebremeskel** [wil3/gymfc#104]
![Screenshot from 2021-07-25 14-23-49](https://user-images.githubusercontent.com/83585542/126897341-7faddbaa-b055-4fdf-83f1-453e94a93098.png)
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wil3** [comment]
Closing, please you correct template
