### ISSUE TITLE
Failed to launch quadcopter

### ISSUE THREAD

**Issue by NahomGebremeskel** [wil3/gymfc#105]
I have followed your installation tutorial, everything installed properly but gazebo failed to launch. 
What could be the problem?
I really need your help!
![Screenshot from 2021-07-25 14-23-49](https://user-images.githubusercontent.com/83585542/126910570-d90c643f-3fec-448b-9e54-debfce611a7d.png)

**Comment by wil3** [comment]
That file path isn't used in the tutorial because it doesn't exist like the error is saying. I suggest watching it again, the digital twins are in the examples directory.

**Comment by wil3** [comment]
From the look at the commands you are trying it appears you aren't familiar with the  Linux command line or python. It would be a good idea to do some basic tutorials such as paths and how to navigate and learn the argparse python library.
