### ISSUE TITLE
Failing to train without internet connection.

### ISSUE THREAD

**Issue by NahomGebremeskel** [wil3/gymfc#107]
I was connected to internet when i started training and the moment i lost connection, the training kind stopped. What could be the problem?

![Screenshot from 2021-08-30 17-13-41](https://user-images.githubusercontent.com/83585542/131353588-94f6f0b0-60c1-463f-b954-6ceefc79075b.png)
### Prerequisites
* [  ] Put an X between the brackets on this line to verify you have done the following:
    * I have checked that your issue isn't already filed.
    * I am running Ubuntu 18.04
    * I installed the environment and GymFC according to these [instructions](https://github.com/wil3/gymfc/#quick-start). 
    
### Steps to Reproduce
Provide the list of commands and the corresponding output. **Do not** post output as images/screenshots. Place output in a fenced [code block](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks). Images are not searchable thus preventing others from finding similar issues and they are difficult to read. 
1. Execute command X
```
Output from command X
```
2. Execute command Y
```
Output from command Y
```
3. See error

**Expected behavior**

**Additional context**

**Comment by wil3** [comment]
Closing, please do not ignore the template.
