### ISSUE TITLE
the empty world model

### ISSUE THREAD

**Issue by Suvian-wy** [wil3/gymfc#108]
Hi, @wil3 . I want to fly my aircraft now. I want to know if the empty env is OK? Do I need to write my own free flight environment？

**Comment by wil3** [comment]
Hey @Suvian-wy, the empty world was initially intended to make sure the model was assembled correctly but could be used to build up a new world. 

To SITL fly your aircraft this is more complicated and outside of the scope of this repo but what you'd have to do is have the model complied into a flight control firmware (e.g., neuroflight) and then interface that with a sim (e.g., Gazebo). 

Its been a really long time but we built this [repo](https://github.com/Aeroloop/betaloop) to SITL fly Betaflight and might be able to point you in the direction for your application.
