### ISSUE TITLE
Can we reduce the feedback rate?

### ISSUE THREAD

**Issue by Kuppharish** [wil3/gymfc#14]
I want to get the state updates 10 times per second rather than 1000. So can we reduce the update rate?

**Comment by wil3** [comment]
Yep just change max_step_size in the Gazebo world file to 0.1,
https://github.com/wil3/gymfc/blob/master/gymfc/envs/assets/gazebo/worlds/attitude-iris.world#L28

For more details on Gazebo world and model files check out the specifications here, http://sdformat.org/spec?elem=physics

That said however I would seriously consider not doing this, your results will be inaccurate. You want the step size to be as fast as your machine will allow, the suggested step size by Gazebo is 0.001. I've had to increase it to 0.0025 to run on laptop though.
