### ISSUE TITLE
How do i visualize the quadcopter simulation ??

### ISSUE THREAD

**Issue by UsamaHamayun1** [wil3/gymfc#15]
Hello Sir, 

I have installed GYMFc according to Instructions mentioned , I also run example code it shows the graph , but How do i visualize the gazebo simulation ???

**Comment by wil3** [comment]
Hi @UsamaHamayun1 please read the ReadMe for how you can render the UI. This is a dup of Issue #3.

**Comment by NahomGebremeskel** [comment]
> Hello Sir,
> 
> I have installed GYMFc according to Instructions mentioned , I also run example code it shows the graph , but How do i visualize the gazebo simulation ???

Can you help me? am stuck on getting the graph.
