### ISSUE TITLE
graph plotting 

### ISSUE THREAD

**Issue by UsamaHamayun1** [wil3/gymfc#18]
Hello Sir, 

Pardon me if i am asking a silly question I have a successfully run your environment with running DDPG algorithm , Luckily I have implemented , But I am unable to Plot graphs Of the episode , 
Please guide me for plotting a graph 
Thankyou

**Comment by wil3** [comment]
Hi @UsamaHamayun1 have you taken a look at the example? You can use that as a reference, https://github.com/wil3/gymfc/blob/master/gymfc/controllers/iris_pid_eval.py. When you evaluate your model just log the true angular velocity (which you can obtain from env.omega_actual) at each time step. You can then use whatever plotting program/library you like with the data. The example uses Matplotlib. Hope that helps.
