### ISSUE TITLE
How can I modify the simulation time?

### ISSUE THREAD

**Issue by xianjiez** [wil3/gymfc#20]
Hi,I want to change the simulation time from 1s to 10s,how can I get it?

**Comment by wil3** [comment]
https://github.com/wil3/gymfc/blob/master/gymfc/__init__.py#L10

**Comment by xianjiez** [comment]
Thank you for your answer and I have another doubt. I saw that there was jitter when the simulation reached the expected value, and what caused the jitter?In the simulation environment, whether a disturbance is added（e.g. wind）？

**Comment by wil3** [comment]
Hi @xianjiez Do you mean from the plots in the paper or the PID example? There is no added disturbances, any observation you see in the step response is from the controller. Jitter is usually a sign of over correction. The jitter in the PID plot is extremely minor and won't be noticeable in flight. Neural networks on the other hand are more difficult to tame.
