### ISSUE TITLE
I want to run OpenAi Gym for hectorquadrotor or Ardrone, I have Ros Kinetic + Gazebo 7 on Ubuntu16.04. 

### ISSUE THREAD

**Issue by wajeehulhassanvii** [wil3/gymfc#24]
Can I setup this repository for working with Ros Kinetic + Gazebo 7 and hectorquadrotor?
Thanks

**Comment by wil3** [comment]
Hi @wajeehulhassanvii GymFC hasn't been tested for 7, only 8 and 9. Version 2 currently in testing is aircraft agnostic so you can use whatever one you want, it doesn't care. As for Ros, what do you need it for?

**Comment by wajeehulhassanvii** [comment]
Thanks for the reply @wil3. I wanted to train a drone using DDPG, I was wondering if I can get OpenAi to work with Ros Kinetic + Gazebo7 on Ubuntu 16.04? I got Ardrone to work on my current setup, just wasn't sure how can I get OpenAi to work with the current project.

**Comment by wil3** [comment]
GymFC v0.1 is an OpenAI environment, the README.md has all the environment names documented on how to initialize it with `gym.make`. GymFC doesn't use Ros, just Gazebo. What are you planning to do with Ros?

**Comment by wajeehulhassanvii** [comment]
I wanted to run drone simulator using ros, it could be Hectorquadrotor, Rotors or Ardrone?

**Comment by wil3** [comment]
Ros is composed of a bunch of modules which can aid in robotic tasks, I was trying to understand what portions of Ros you need and if it makes sense for using GymFC. In either case Ros and Gazebo 7 aren't currently supported and there is no plan to support older versions of Gazebo. If you are able to get it working please submit a PR. 

As for using other aircraft, as I previously mentioned v0.2 will be able to support this.
