### ISSUE TITLE
Running simulation visualization

### ISSUE THREAD

**Issue by zbenic** [wil3/gymfc#3]
Hello,

I have given up on trying for Gazebo to work on Win10.
On Ubuntu, I had no problems what so ever.

I was able to run your test script and got the referent result.
I will probably use Gazebo in headless mode 99% of the time, it would still be nice to be able to make some videos of the simulations.
How can I visualize the simulation?

I've tried with changing the line
`p = subprocess.Popen(["gzserver", "--verbose", target_world], shell=False)`
to
`p = subprocess.Popen(["gzclient", "--verbose", target_world], shell=False)`

but just got a bunch of:
`Exception occured connecting to Gazebo retrying .... [Errno 111] Connect call failed ('127.0.0.1', 11345)`

Do you have any suggestion?

**Comment by wil3** [comment]
Hi @zbenic I had a similar issue trying to get it to run on centos with no luck.

Funny you mention this I was just adding this code in. Do a pull to get the new code and after you create your environment call `env.render()`. It helps if you add a command line argument to your script if you want to visualize the simulation.
