### ISSUE TITLE
which version of protobuf ?

### ISSUE THREAD

**Issue by weixingsun** [wil3/gymfc#30]
I got error when using protobuf 3.9.1:
/usr/include/ignition/msgs1/ignition/msgs/material.pb.h: In member function ‘const string& ignition::msgs::Material::normal_map() const’:
/usr/include/ignition/msgs1/ignition/msgs/material.pb.h:662:93: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return normal_map_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

also error when using 3.5.1:
error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’

**Comment by wil3** [comment]
3.0.0, which also appears to be the only one available in the 18.04 repo, 
`sudo apt-cache madison libprotoc-dev`

How did you go about getting that version installed?
