### ISSUE TITLE
A confusion

### ISSUE THREAD

**Issue by COST-97** [wil3/gymfc#32]
I am more interested in your work. After reading your paper, I found your code here. One of my confusion is how do you specifically implement the reward function in your code? Could you please give me a hint. thank you very much!

**Comment by wil3** [comment]
Hi @COST-97, I finished my PhD at BU at the end of the summer so this work is being transitioned by a new team. They are currently working on updates and a new paper, hopefully we will see something soon.

In the mean time my [thesis](http://wfk.io/docs/WilliamKochThesisFINAL.pdf) is very detailed from model creation to the latest reward function (Section 5.4.1 Alg. 2). The reward algorithm is basically pseudo code needed. Hope this helps.

If you are referring to the code used in the TCPS manuscript though, that has been tagged off [here](https://github.com/wil3/gymfc/releases/tag/v0.1.0) but if you've read my follow up work that won't get you flying in the real world, you'll need the new reward function.
