### ISSUE TITLE
Error: Model_sdf not defined 

### ISSUE THREAD

**Issue by sbaktha** [wil3/gymfc#33]
I am running the following command inside a venv: `python tests/test_start_sim.py gymfc/envs/assets/gazebo/models/attitude_control_training_rig/model.sdf`
I have the plugins in the correct directory but I'm getting the following error. 

Traceback (most recent call last):
  File "tests/test_start_sim.py", line 32, in <module>
    env = Sim(args.aircraftconfig, args.gymfc_config, args.verbose)
  File "tests/test_start_sim.py", line 10, in __init__
    super().__init__(aircraft_config, config_filepath=config, verbose=verbose)
  File "/home/baktha/baktha/repos/AI_Sim/gymfc/gymfc/envs/fc_env.py", line 145, in __init__
    self.load_config(aircraft_config, config_filepath = config_filepath)
  File "/home/baktha/baktha/repos/AI_Sim/gymfc/gymfc/envs/fc_env.py", line 235, in load_config
    self._parse_model_sdf()
  File "/home/baktha/baktha/repos/AI_Sim/gymfc/gymfc/envs/fc_env.py", line 381, in _parse_model_sdf
    raise SystemExit("Could not find plugin with filename {} from SDF file {} required to load the aircraft model.".format("libAircraftConfigPlugin.so", model_sdf))
NameError: name 'model_sdf' is not defined

Any idea on how to solve it?

**Comment by wil3** [comment]
Hi @sbaktha, the command line parameter for the SDF is for the aircraft SDF. The SDF you are providing is the apparatus used in GymFC for training, its not an aircraft. 

GymFC2 is meant to train neuroflight controllers for the real world and thus you must provide a model of the aircraft you plan to fly in the real world. This part of the project needs most help, we really need help with model creation. It would be very useful to have a model of an off-the-shelf commonly used quadcopter, but to train well it needs to be aerobatic. If you're able to read my [thesis](http://wfk.io/docs/WilliamKochThesisFINAL.pdf) this will all make more sense. 

We started migrating the Solo model (linked at the README.md) to GymFC and there is a PR for doing a demo with it, best to start there.
