### ISSUE TITLE
Can you provide the iris model

### ISSUE THREAD

**Issue by Yan-Wang747** [wil3/gymfc#36]
Hi, 
I am trying to run this project. Could you please provide the drone model you used for your manuscript?

Thanks,

**Comment by wil3** [comment]
It should be this tagged version https://github.com/wil3/gymfc/releases/tag/v0.1.0
but if you read our follow up work / my thesis the gymfc1 reward system will not allow the quad to transfer to the real world, it is highly recommended to use what is in master.

I'm in the process of preparing the new NF1 models for release.

**Comment by wil3** [comment]
Closing since there's been no follow up.
