### ISSUE TITLE
test_start_sim.py wont find components and run

### ISSUE THREAD

**Issue by xabierolaz** [wil3/gymfc#38]
Hi, im dealing some issues with running test environments,
Whenever I try to run **test_start_sim.py**
`(env) cuda@eim-alu-83252:~/projects/gymfc/tests$ python3 test_start_sim.py ~/nf1/model.sdf`
I get this error:
`Default configuration file at /home/cuda/projects/gymfc/env/lib/python3.6/site-packages/gymfc/envs/../../gymfc.ini missing, aborting`

Im using **nf1** model from the **thesis-work** branch 
so I went to the source code, and searched for that line, it’s inside the **gymfc/envs/fc_env.py** file :
![environ1](https://user-images.githubusercontent.com/31626226/77906264-f385b900-7287-11ea-8ba4-68d8525a9468.JPG)

so I guess it’s looking for **gymfc.ini** and not finding it inside current dir

test_start_sim.py is in gymfc/tests/**test_start_sim.py**, so wont be able to find gymfc.ini as its one directory up in gymfc/**gymfc.ini**, so Ive tried moving test_start_sim.py to project’s root folder ‘gymfc’ and running from there:

`python3 test_start_sim.py ~/nf1/model.sdf`

but then I get this new error:

`Could not find Gazebo setup.sh file at '/home/$USER/local/share/gazebo-10/setup.sh'. Typo?`

So I went there and **setup.sh** is clearly there, as I had pointed before inside the **gymfc.ini** file:
![pic2](https://user-images.githubusercontent.com/31626226/77906460-4b242480-7288-11ea-84e1-ff1f7c97a1bf.JPG)

Any hints? Must be something trivial but have not been able to find the issue so far

**Comment by wil3** [comment]
> (env) cuda@eim-alu-83252:~/projects/gymfc/tests$ python3 test_start_sim.py ~/nf1/model.sdf

The first issue is unless you moved the default location of the model this isn't the correct command. It should be,

`python3 test_start_sim.py ../modules/digitaltwins/nf1/model.sdf`

Looking at the error message you are seeing your install path of gymfc looks like it wasn't installed in development mode (i.e., pip3 install -e .). If you look in ` /home/cuda/projects/gymfc/env/lib/python3.6/site-packages/gymfc/`you will indeed not find gymfc.ini (wouldn't make sense to put a config file there). If you choose to install it this way that is fine but you need to tell gymfc where that ini file is.

There are a couple ways to specify the gymfc.ini file. The first,  as the code you linked suggests, is to set it to the environment variable, 

`export GYMFC_CONFIG=../gymfc.ini; python3 test_start_sim.py ../modules/digitaltwins/nf1/model.sdf`

The second way is to provide it as a command line argument when running the test,

`python3 test_start_sim.py ../modules/digitaltwins/nf1/model.sdf --gymfc-config ../gymfc.ini`

Hope that helps.

**Comment by xabierolaz** [comment]
Thanks for the response!
Tried reinstalling as developer and **got gazebo running** when running the test:
```
(env) cuda@eim-alu-83252:~/projects/gymfc/tests$ python3 test_start_sim.py ../modules/digitaltwins/nf1/model.sdf --gymfc-config ../gymfc.ini
Sending motor control signals to port  9676
Gazebo Model Path = /home/cuda/local/share/gazebo-10/models::/home/cuda/projects/gymfc/env/lib/python3.6/site-packages/gymfc/envs/assets/gazebo/models:/home/cuda/projects/gymfc/modules/digitaltwins
Gazebo Plugin Path = /home/cuda/local/lib/gazebo-10/plugins::/home/cuda/projects/gymfc/env/lib/python3.6/site-packages/gymfc/envs/assets/gazebo/plugins/build:/home/cuda/projects/gymfc/modules/digitaltwins/nf1/plugins/build
Starting gzserver with process ID= 4477
```

However, when gazebo starts **there is no** Neuroflight1 **model placed**, I have to manually go to the Insert tab inside gazebo and drag it into the scene.
![Captura](https://user-images.githubusercontent.com/31626226/78659983-995ea680-78cc-11ea-8920-dc570380c182.JPG)


EDIT: I'm getting this error once gazebo gets started:
`(env) cuda@eim-alu-83252:~/projects/gymfc/tests$ Error Code 11 Msg: Unable to find uri[model://attitude_control_training_rig]
`

**Comment by wil3** [comment]
What does your World tab look like in Gazebo?

There's something wrong with your install, look at your model and plugin paths...its pointing to two different locations, you may not have uninstalled the other gymfc. Make sure you are using virtual environments to prevent clashes like this. 

In the future if you have a separate issue could you please open a new one up?

**Comment by xabierolaz** [comment]
Everything seems to work now, **it was all about the gymfc install as you pointed out**, tried with a clean spnapshot, reinstalled and its fixed thanks!

![Captura](https://user-images.githubusercontent.com/31626226/78777168-57e7fd00-7999-11ea-8c6a-fcca75b3645c.JPG)

**Comment by wil3** [comment]
Awesome! Glad to hear!
