### ISSUE TITLE
Error in running make command while installing Gazebo

### ISSUE THREAD

**Issue by varunag18** [wil3/gymfc#52]
Trying to setup gymfc on my Ubuntu 18.04. Installed DART 6.7.0 correctly. 
Following the steps mentioned in [http://gazebosim.org/tutorials?tut=install_from_source&cat=install](url) to install Gazebo 10.2.0, but facing the below error on running the make command.
![GazeboError](https://user-images.githubusercontent.com/1232584/80800931-71f7b280-8bc8-11ea-87a3-850e7d8c46a8.jpg)
Running ` cmake -DCMAKE_BUILD_TYPE=Debug ../` completed successfully, with only some warnings, no errors.
Running the command `ls /etc/apt/sources.list.d/ | grep dart` returns:
`dartsim-ubuntu-ppa-bionic.list`
`dartsim-ubuntu-ppa-bionic.list.save`
So, i believe my DART has installed successfully. Sorry, Im new to ubuntu, may be making a silly error.
Thanks in advance.
Varun

**Comment by wil3** [comment]
Hi Varun,
Nothing to be sorry about, setting this environment up isn't the easiest task. It might be helpful to reference the steps [here](https://github.com/wil3/gymfc/blob/i50-travis/.travs.yml) and [here](https://github.com/wil3/gymfc/blob/master/Dockerfile-demo). These scripts are known to work to build the environment. Make sure you start off at a clean state though.

**Comment by varunag18** [comment]
I have installed Gymfc sucessfully using the links u mentioned. However, im nt sure if my installation is fully correct. When I am in the folder /gymfc and run the following code at the terminal:
`python`
`>>>import gymfc`
I dont get any error.
However, when I navigate to a subfolder in my directory, say /gymfc/tests and again execute the above code, i get the `ModuleNotFoundError: No module named 'gymfc' ` error. 
Once iv setup the whole thing in a Conda virtual environment, the code should should work everywhere within the environment and not just from a single location.
There is some elementary mistake i am making, owing to my lack of knowledge of Ubuntu and python in general. 
A couple of more questions i would like to add, though im not sure if i should be asking them here or opening a separate issue for it. I am trying to test some reinforcement learning algos on UAVs, and for that i have installed the Open AI baselines package. 

1. When I run the below command in the /gymfc folder:
`python run_gymfc.py --env=AttFC_GyroErr-MotorVel_M4_Ep-v0`
I get the below error: 
`UnregisteredEnv: No registered env with id: AttFC_GyroErr-MotorVel_M4_Ep-v0`

![err](https://user-images.githubusercontent.com/1232584/81163950-24ef5400-8fad-11ea-887a-d7c5182fc892.jpg)

2. After installing the baselines, I tried testing the installation with the following code:
`pip install pytest`
`pytest`
I get the error
`ImportError while importing test module '/gymfc/tests/test_axis.py'.`
`tests/test_axis.py:3: in <module>`
`    from gymfc.envs.fc_env import FlightControlEnv`
`E   ModuleNotFoundError: No module named 'gymfc'`

Below is the screenshot of the same

![err1](https://user-images.githubusercontent.com/1232584/81166114-cfb54180-8fb0-11ea-9d18-018f89d2bcfb.jpg)


3. Is there some Readme file or a help document that describes the process of coding to obtain Gymfc, baseline algo like DDPG and Gazebo? Not sure if im asking too much ;)
Thanks in advance.

**Comment by wil3** [comment]
Hi @varunag18,
It almost appears as if you have gymfcv1 installed. The environment AttFC_GyroErr-MotorVel_M4_Ep-v0 existed in v1 and does not exist in v2 as gymfc has moved to a more generic architecture.  What is the file `run_gymfc.py` ?

If you aren't running gymfc in a virtual environment I recommend doing so and install it via pip in development mode (i.e., with the -e flag). The readme has the instructions for this. I've never run it via ipython so I'm not sure of the expected behavior. 

For my thesis I used [this](https://github.com/wil3/openai-baseline) fork of OpenAI baselines. If you haven't done so already check out my thesis for more information on the changes from v1 to v2. I have a [branch](https://github.com/wil3/gymfc/tree/thesis-work) I'm adding the rest of my thesis work to including the openai gym environments. If you have a look at the test scripts in /tests you'll see how environments are created.

Before trying to train make sure you can successfully run through all of the test scripts. If you do not have your own aircraft model you can use the NF1 model in my thesis branch for the time being.

**Comment by varunag18** [comment]
Hi Wil, first of all, thnx fr ur prompt replies. I am still facing issues with the installation. In the 4th step, where i need to manually build the plugin running the script `gymfc/envs/assets/gazebo/plugins/build_plugin.sh` gives me the following error: `fatal error: gazebo/physics/dart/DARTModel.hh: No such file or directory` in the file `gymfc/envs/assets/gazebo/plugins/FlightControllerPlugin.cpp`. 
![Screenshot from 2020-05-12 10-15-41](https://user-images.githubusercontent.com/1232584/81639799-99594580-943a-11ea-8a10-2e73d99b456f.png)
Is it something like Gazebo not being able to locate Dart, though I have installed it.

When I run the test script `python3 test_start_sim.py ../examples/gymfc_nf/twins/nf1/model.sdf --gymfc-config ../gymfc.ini` from my /gymfc/tests folder, I get the following error. `Could not find Gazebo plugins. If you have installed in development mode these must be built manually. Please refer to /home/gymfc/gymfc/gymfc/envs/assets/gazebo/plugins/README.md for manually building the plugins.` 
If u suggest, I can do a fresh install of everything, DART, Gazebo and then GymFc. Will creating a new user in Ubuntu and installing everything on it, be sufficient?

**Comment by wil3** [comment]
That error is saying it can't find the gazebo header. Usually this means there was a problem with your gazebo install. 

If you take a look at the gazebo install from source [doc](http://gazebosim.org/tutorials?tut=install_from_source&cat=install) there is a section titled "**Local Install**". Have you made sure your install has been added to the correct environment variables?

**Comment by varunag18** [comment]
Hi Wil, my Gazebo is installed correctly. Running `gazebo` command from the terminal loads the software correctly. However, I still updated the paths in the bashrc file, you mentioned above. The error is still the same, as above.
Also, any thoughts on the Gazebo Dart error mentioned in the screenshot above.

**Comment by xabierolaz** [comment]
Hi @varunag18, did you change the gymfc.ini file so it points to your gazebo path?

**Comment by wil3** [comment]
Can you provide the full output of running `build_plugin.sh`?  Difficult to know the state of your system without this information.

**Comment by varunag18** [comment]
> Can you provide the full output of running `build_plugin.sh`? Difficult to know the state of your system without this information.

I have removed my earlier installation of gymfc and done a fresh install using the [dockerfile](https://github.com/wil3/gymfc/blob/master/Dockerfile-demo). I run a test script to check if installation is correct and I receive `ModuleNotFoundError: No Module named 'gymfc' ` error. Attaching a screenshot below:
![Screenshot from 2020-05-15 23-57-14](https://user-images.githubusercontent.com/1232584/82083864-005f4e80-9708-11ea-92d9-e950abe54eeb.png)

When I am in the folder /gymfc and run the following code at the terminal:
`python`
`>>>import gymfc`
I dont get any error.
However, when I navigate to a subfolder in my directory, say /gymfc/tests and again execute the above code, i get the `ModuleNotFoundError: No module named 'gymfc'` error. Any clue why this is happening? 
Also, I try to manually build the plugin running the script gymfc/envs/assets/gazebo/plugins/build_plugin.sh, I receive the same error as earlier. [Attached](https://pastebin.ubuntu.com/p/Y9HmBG77xy/) the output of the `build_plugin.sh`.
The `/usr/include/gazebo-10/gazebo/physics` directory does not have a `dart` folder. 
For the record, im adding the terminal's [output](https://pastebin.ubuntu.com/p/TSwfmn7zF6/) of the docker build. May me of help.

**Comment by varunag18** [comment]
> Hi @varunag18, did you change the gymfc.ini file so it points to your gazebo path?

The gymfc.ini file has the following content. 
`SetupFile = $HOME/local/share/gazebo/setup.sh`, which seems to me to be reflecting the correct location. Please correct me if I am wrong.
![gazebo path](https://user-images.githubusercontent.com/1232584/82085428-a4e29000-970a-11ea-953e-3bf69fa29e40.jpg)



I have changed the SetupFile path in gymfc.ini from gazebo to gazebo-10 once, but no difference in result.

**Comment by varunag18** [comment]
After many attempts at uninstalls and re-installs, iv managed to finally get gymfc installed successfully. I ran the test scripts in the tests subfolder and they are running. Thanks Wil and @xabierolaz for all the help. its really heartening when you are new to a field and there is some help around.

**Comment by lookingforfeng** [comment]
> After many attempts at uninstalls and re-installs, iv managed to finally get gymfc installed successfully. I ran the test scripts in the tests subfolder and they are running. Thanks Wil and @xabierolaz for all the help. its really heartening when you are new to a field and there is some help around.
> 
> 在多次尝试卸载和重新安装之后，iv 终于成功安装了 gymfc。我在测试子文件夹中运行了测试脚本，它们正在运行。感谢 Wil 和@xabierolaz 的帮助。当你刚进入这个领域，有人帮助你的时候，这真的很振奋人心。

how did you  solve it
