### ISSUE TITLE
Other RL Controllers

### ISSUE THREAD

**Issue by leonardoaraujosantos** [wil3/gymfc#6]
Hi @wil3 you will include other types of RL controllers like PPO/TRPO?

Thanks

**Comment by lengjia** [comment]
I have the same problems in using baselines algorithms of PPO/TRPO, can you give the source code of RL controllers? @wil3

**Comment by wil3** [comment]
Hi @leonardoaraujosantos and @lengjia , please read our paper and the README file, this is a gym environment, not a repo for controllers. Our work used the OpenAI baselines repo to construct RL controllers. The PID controller is only given as a means to ensure the environment is operating correctly and provide a baseline for any other RL controllers you develop.

**Comment by lengjia** [comment]
got it! thanks so much!

**Comment by cbekar** [comment]
Lack of RL glue code makes reproducing the paper's results somewhat cumbersome.
