### ISSUE TITLE
Other option besides Gazebo

### ISSUE THREAD

**Issue by leonardoaraujosantos** [wil3/gymfc#7]
Hi @wil3 
Silly question but did you consider using Unity ML agents to build the Quad simulator?
* https://github.com/Unity-Technologies/ml-agents
* https://blogs.unity3d.com/pt/2018/02/28/introducing-the-winners-of-the-first-ml-agents-challenge/

Thanks

**Comment by wil3** [comment]
Hi @leonardoaraujosantos, 
Gazebo is already widely used for flight controller SITL testing (eg Cleanflight, Betaflight, Arducopter, PX4, etc) so there already existed a quadcopter model and interface to the simulator which made the design decision to use Gazebo easy. Remember, the goal GymFC is be able to transfer the neural network into a flight control system. No other simulator I have come across is used or supports as many FCs as Gazebo. Although other simulators provide better graphics, only the physics engine is important for GymFC, no image processing is happening. Gazebo also supports multiple different physics engines.

I have no time to support any other backends and I havn't come across any reasons that would justify the effort but it is certainly possible. I'm happy to accept PRs if anyone is up for doing this. Thanks,
